### ISSUE TITLE
Fehlender Persistenter DB Speicher in Docker Installation Beispiel

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/Schild3-BetaTest#1132]
Hallo zusammen,

ich habe noch einen kleinen Verbesserungsvorschlag für die Doku zur Docker Installation. Hier würde ich noch einen Hinweis zum persistenten Volume für die DB machen. Entweder kann das Volume ja dann für die Docker Compose einfach in Docker angelegt werden oder man mountet das Volume auf die eigene Festplatte. Ich finde es aber durchaus gefährlich, wenn das persistente Volume hier vergessen wird, denn so könnten ggf. wichtige Daten verloren gehen.

```yaml
service:
  mariadb:
    ...
    volumes:
      - path/to/my/persistent/volume:/var/lib/mysql
```
